tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "lotyp/homebrew-formulae" # needed for dockutil

brew "bandwhich" # network utilization tool (needs sudo)
brew "bat" # cat with syntax highlighting
brew "bottom" # top replacement, system dashboard
brew "coreutils" # better core /usr/bin
brew "diskonaut" # disk/folder space utilization
brew "duf"
brew "dust"
brew "duti" # set default OSX apps
brew "exa" # better ls
brew "fd" # find things easily
brew "ffmpeg"
brew "fish"
brew "fnm" # NVM but in rust
brew "fzf" # fuzzy search (used by zsh fzf-tab for autocomplete)
brew "git"
brew "git-delta" # awesome git diffs
brew "hyperfine" # benchmark commands
brew "jq" # parse json from bash
brew "lotyp/formulae/dockutil"
brew "mas"
brew "monolith" # download websites
brew "neovim"
brew "ouch" # zip/unzip stuff easily
brew "poppler" # preview pdf files (used by yazi)
brew "pueue" # long running tasks queue
brew "ripgrep" # better faster grep
brew "serve"
brew "shellcheck"
brew "speedtest-cli"
brew "starship"
brew "tealdeer" # aint nobody got time for that
brew "unar" # The Unarchiver for terminal, improves yazi
brew "wget"
brew "xplr" # TUI file manager user friendly
brew "yarn"
brew "yazi" # TUI file manager with preview
brew "youtube-dl"
brew "yt-dlp"
brew "zsh"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

cask "choosy"
cask "docker"
cask "firefox", args: { 'no-quarantine': true }
# cask "firefox-developer-edition"
cask "font-lato"
cask "font-lora"
cask "font-meslo-lg-nerd-font"
cask "font-nunito"
cask "font-nunito-sans"
cask "font-raleway"
cask "font-source-sans-3"
cask "font-source-serif-4"
cask "font-symbols-only-nerd-font" # needed by yazi
cask "google-chrome" , args: { 'no-quarantine': true }
cask "insomnia"
cask "iterm2"
cask "kap"
cask "kitty"
cask "numi"
cask "qlmarkdown", args: { 'no-quarantine': true }
cask "quicklook-json"
cask "slack"
cask "spotify"
cask "stats", args: { 'no-quarantine': true }
cask "sublime-text"
cask "visual-studio-code" , args: { 'no-quarantine': true }
cask "vlc", args: { 'no-quarantine': true }
cask "whatsapp"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Simplenote", id: 692867256
mas "Ghostery – Privacy Ad Blocker", id: 1436953057
mas "MeetingBar", id: 1532419400
mas "New File Menu Lite", id: 1066302071
mas "NordVPN", id: 905953485
mas "GrandPerspective", id: 1111570163
mas "Telegram Lite", id: 946399090
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637

vscode "christian-kohler.npm-intellisense"
vscode "clinyong.vscode-css-modules"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "foxundermoon.shell-format"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mechatroner.rainbow-csv"
vscode "mrmlnc.vscode-scss"
vscode "MylesMurphy.prettify-ts"
vscode "PKief.material-icon-theme"
vscode "syler.sass-indented"
vscode "streetsidesoftware.code-spell-checker"
vscode "timonwong.shellcheck"
vscode "tomoki1207.pdf"
vscode "yoavbls.pretty-ts-errors"
